version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: task_user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      DATABASE_URI: mysql+pymysql://task_user:user123@db/tasks_db
      JWT_SECRET_KEY: "123456"
      MYSQL_USER: task_user
      MYSQL_PASSWORD: user123
      MYSQL_HOST: db
      MYSQL_DB: tasks_db
      MYSQL_PORT: 3306
    volumes:
      - .:/app
